Staff Endpoints
ChangePlusPlusVandy/NewMissionSafe-backend pull request #2
Opened 2023-11-30 22:05 UTC by txingxie

2023-12-03 08:54 UTC, samshefnie requested changes

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +    res.status(500).send(err);
For error handling it's best to send descriptive information to the user instead of just a 500 status error. I recommend using the same format for error handling as the one used in the event router file.

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +    let newStaff = await createStaff(req.body);
newStaff should be a const variable since its value should not change after assignment. It seems like multiple routes are like this so they should be changed too.

2023-12-03 08:54 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +  const staff = await StaffModel.findOne({ email });
I would recommend using the format {attributeName: attributeValue} (i.e. {email: emailValue} instead of just {email} )for parameters in the mongoose find functions. This is so that there is greater readability in what attribute is being searched for. Refer to this [link](https://mongoosejs.com/docs/api/model.html#Model.findOne()) for more info.

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +const {
These methods should be imported using the 'import' statement not a 'require' statement.

2023-12-03 08:54 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +import { StaffModel, staffType } from "../models/staff";
You should import staffType as a type

2023-12-03 08:54 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +export const getStaffByProgram = async (programs: string[]) => {
The programs parameter should be of type String instead of String[] because the method should only query for one program at a time

2023-12-03 08:54 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +  if (!staff) throw new Error("Staff not found");
It is better to send descriptive errors using the HTTPErrors class that can be found in the src/utils folder. I recommend following the same format for error handling as in the events.controller file for all methods in this file.

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +staffRouter.put("/updateFirstName/:firebaseUID", async (req, res) => {
I think the updateFirstName, updateLastName, and UpdateEmail routes can be consolidated into one route and just have the key also be passed as a parameter from req.body. @lunstb lmk if you agree.

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +    await updateStaff(req.params.firebaseUID, { key: "active", value: false });
value should be true for the activate endpoint

2023-12-03 08:54 UTC, samshefnie commented on src/routers/staff.router.ts
> +    await updateStaffActive(req.params.firebaseUID, {
Why are you using updateStaff for the activate endpoint, but updateStaffActive for the deactivate endpoint?

2023-12-06 21:38 UTC, lunstb commented on src/controllers/staff.controller.ts
> +  if (!staff) throw new Error("Staff not found");
second this

2023-12-06 21:45 UTC, lunstb requested changes
Looks great overall, just a few things to clean up!

2023-12-06 21:45 UTC, lunstb commented on src/routers/staff.router.ts
> +    res.status(404).send(err);
Raw errors probably shouldn't be sent directly back to the user: https://stackoverflow.com/questions/67290510/whether-all-error-messages-should-come-from-the-backend-in-a-form-that-can-be-sh 

Maybe this should be logged then a cleaner human readable version should be sent to the user. @samshefnie do we have a clean way of logging things to a file set up for this project yet?

2023-12-06 21:45 UTC, lunstb commented on src/routers/staff.router.ts
> +    res.status(404).send(err);
Same comment here (and places below, I'm not going to copy paste)

2023-12-07 23:17 UTC, BobbyMi11er commented on src/routers/staff.router.ts
> +staffRouter.get("/byPrograms/:programs", async (req, res) => {
This is by program, not email

2024-01-09 23:50 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +    const staff = await StaffModel.findOne({ firebaseUID: firebaseUIDValue });
This should throw an error if there is no staff with the given firebaseID (in other words an error should be thrown if staff is null).

2024-01-09 23:50 UTC, samshefnie commented on src/routers/staff.router.ts
> +// // PUT new firstName
these comments should be deleted if not needed anymore

2024-01-09 23:50 UTC, samshefnie commented on src/controllers/staff.controller.ts
> +    const staff = await StaffModel.find({ program: programValue });
should be programs not program

2024-01-11 18:11 UTC, samshefnie approved these changes
looks good

2024-01-22 16:50 UTC, lunstb approved these changes

2024-01-22 22:04 UTC, merged