Event Endpoints Update
ChangePlusPlusVandy/NewMissionSafe-backend pull request #4
Opened 2023-12-03 20:54 UTC by jackgarritano

- Adds types to req parameter for linter
- Adds function in errors folder to intercept mongoose errors and give a more specific http error code and message

2023-12-06 20:55 UTC, samshefnie commented on src/controllers/event.controller.ts
Your new edits look fine, but there's one thing I missed commenting on in your original commit. The mongoose find method will always return an array so in lines 8 and 33 instead of having !events as the conditional for the if statement, it should be events.length === 0. Having !events as the conditional will return true for an empty array (since it is not of type null) and we won't be able to throw the right errors.

2023-12-06 20:57 UTC, samshefnie commented on src/utils/errors.ts
good work!

2023-12-06 21:28 UTC, lunstb requested changes
Check Sam's comments. Love the parsing of Mongoose errors tho

2023-12-06 21:28 UTC, lunstb commented on src/utils/errors.ts
> +export function checkMongooseErrors(err: unknown) {
yay :) this makes me happy

2023-12-07 01:28 UTC, jackgarritano commented on src/controllers/event.controller.ts
Thanks, I updated both find() calls. One thing, for the getAllEvents function, would it make sense to remove that check entirely? From the frontend pov it seems like they might prefer getting back an empty array if there are no events instead of an error.

2023-12-07 21:27 UTC, samshefnie commented on src/controllers/event.controller.ts
i like that idea.

2023-12-07 23:14 UTC, jackgarritano commented on src/controllers/event.controller.ts
Alright, I removed that empty check in getAllEvents, I think should be good to merge now.

2024-01-09 23:52 UTC, samshefnie approved these changes

2024-01-11 03:01 UTC, lunstb approved these changes
lgtm

2024-01-11 03:55 UTC, merged